version: '3.3'
services:
  collabora:
    image: collabora/code:latest
    container_name: collabora_app
    networks:
      - traefik_proxy
    cap_add:
      - MKNOD
    expose:
      - 9980
    environment:
      - domain=nextcloud.domain #Gebt hier eure Nextcloud Domain an. Wenn ihr dies nicht nutzt, dann entfernt diese Zeile
      - username=adminuser     #Nutzername eingeben
      - password=        #Passwort eingeben
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.entrypoints=http"
      - "traefik.http.routers.collabora.rule=Host(`sub.domain.tld`)"  #URL anpassen
      - "traefik.http.middlewares.collabora-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.collabora.middlewares=collabora-https-redirect"
      - "traefik.http.routers.collabora-secure.entrypoints=https"
      - "traefik.http.routers.collabora-secure.rule=Host(`sub.domain.tld`)"  #URL anpassen
      - "traefik.http.routers.collabora-secure.tls=true"
      - "traefik.http.routers.collabora-secure.tls.certresolver=http"
      - "traefik.http.routers.collabora-secure.service=collabora"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.collabora-secure.middlewares=secHeaders@file"
networks:
  traefik_proxy:
    external: true
