version: '3'
services:
  bitwarden:
    image: bitwardenrs/server:latest
    restart: unless-stopped
    volumes:
       - /opt/docker/bitwarden/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.entrypoints=http"
      - "traefik.http.routers.bitwarden.rule=Host(`sub.domain.tld`)" ## Hier anpassen ##
      - "traefik.http.middlewares.bitwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bitwarden.middlewares=bitwarden-https-redirect"
      - "traefik.http.routers.bitwarden-secure.entrypoints=https"
      - "traefik.http.routers.bitwarden-secure.rule=Host(`sub.domain.tld`)" ## Hier anpassen ##
      - "traefik.http.routers.bitwarden-secure.tls=true"
      - "traefik.http.routers.bitwarden-secure.tls.certresolver=http"
      - "traefik.http.routers.bitwarden-secure.service=bitwarden"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.bitwarden-secure.middlewares=secHeaders@file"
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true